import {
  INDEX_VAULT_ABI,
  PDOT_ABI,
  PDOT_ADDRESS,
  REGISTRY_ABI,
  REGISTRY_ADDRESS,
  ROUTER_ABI,
  ROUTER_ADDRESS,
  VAULT_ADDRESS,
  XCM_DEMO_ABI,
  XCM_DEMO_ADDRESS,
} from "@/generated/contracts.generated";

export { VAULT_ADDRESS, PDOT_ADDRESS, REGISTRY_ADDRESS, ROUTER_ADDRESS, XCM_DEMO_ADDRESS };
export { INDEX_VAULT_ABI, PDOT_ABI, REGISTRY_ABI, ROUTER_ABI, XCM_DEMO_ABI };
