import fs from "node:fs";
import path from "node:path";

type Artifact = {
  abi: unknown[];
};

type Deployments = {
  uniswap?: {
    router?: string;
  };
  core?: {
    indexVault?: string;
    pdotToken?: string;
    tokenRegistry?: string;
    xcmDemo?: string;
  };
};

const ROOT = process.cwd();
const GENERATED_DIR = path.join(ROOT, "app", "src", "generated");

function readJson<T>(relativePath: string): T {
  const absolutePath = path.join(ROOT, relativePath);
  return JSON.parse(fs.readFileSync(absolutePath, "utf8")) as T;
}

function writeFile(relativePath: string, contents: string): void {
  const absolutePath = path.join(ROOT, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, contents, "utf8");
}

function pickAgentSamplePath(): string {
  const preferred = path.join(ROOT, "agent", "sample-output", "dry-run-sample.json");
  if (fs.existsSync(preferred)) {
    return preferred;
  }

  const dir = path.join(ROOT, "agent", "sample-output");
  if (!fs.existsSync(dir)) {
    throw new Error("agent/sample-output directory is missing");
  }

  const candidates = fs
    .readdirSync(dir)
    .filter((name) => /^dry-run-.*\.json$/.test(name))
    .map((name) => path.join(dir, name));

  if (candidates.length === 0) {
    throw new Error("No dry-run sample JSON found in agent/sample-output");
  }

  candidates.sort((a, b) => fs.statSync(b).mtimeMs - fs.statSync(a).mtimeMs);
  return candidates[0];
}

function main(): void {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });

  const deployments = readJson<Deployments>("deployments/testnet.json");
  const indexVault = readJson<Artifact>("artifacts/contracts/IndexVault.sol/IndexVault.json");
  const pdot = readJson<Artifact>("artifacts/contracts/PDOTToken.sol/PDOTToken.json");
  const registry = readJson<Artifact>("artifacts/contracts/TokenRegistry.sol/TokenRegistry.json");
  const router = readJson<Artifact>("artifacts/contracts/uniswap/UniswapV2Router02.sol/UniswapV2Router02.json");
  const xcmDemo = readJson<Artifact>("artifacts/contracts/XcmDemo.sol/XcmDemo.json");

  const contractsSource = `/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/* Generated by: bun run sync:app */

export const VAULT_ADDRESS = ${JSON.stringify(
    deployments.core?.indexVault ?? "0x0000000000000000000000000000000000000000"
  )} as const;
export const PDOT_ADDRESS = ${JSON.stringify(
    deployments.core?.pdotToken ?? "0x0000000000000000000000000000000000000000"
  )} as const;
export const REGISTRY_ADDRESS = ${JSON.stringify(
    deployments.core?.tokenRegistry ?? "0x0000000000000000000000000000000000000000"
  )} as const;
export const ROUTER_ADDRESS = ${JSON.stringify(
    deployments.uniswap?.router ?? "0x0000000000000000000000000000000000000000"
  )} as const;
export const XCM_DEMO_ADDRESS = ${JSON.stringify(
    deployments.core?.xcmDemo ?? "0x0000000000000000000000000000000000000000"
  )} as const;

export const INDEX_VAULT_ABI = ${JSON.stringify(indexVault.abi, null, 2)} as const;
export const PDOT_ABI = ${JSON.stringify(pdot.abi, null, 2)} as const;
export const REGISTRY_ABI = ${JSON.stringify(registry.abi, null, 2)} as const;
export const ROUTER_ABI = ${JSON.stringify(router.abi, null, 2)} as const;
export const XCM_DEMO_ABI = ${JSON.stringify(xcmDemo.abi, null, 2)} as const;
`;

  writeFile("app/src/generated/contracts.generated.ts", contractsSource);

  const samplePath = pickAgentSamplePath();
  const sampleRaw = fs.readFileSync(samplePath, "utf8");
  const sampleJson = JSON.parse(sampleRaw) as unknown;

  const planPayload = (sampleJson as { payload?: unknown; newTargets?: unknown }).payload
    ? (sampleJson as { payload: unknown }).payload
    : sampleJson;

  const sampleSource = `/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/* Generated by: bun run sync:app */

export const AGENT_PLAN_SAMPLE = ${JSON.stringify(planPayload, null, 2)} as const;
`;

  writeFile("app/src/generated/agent-plan-sample.generated.ts", sampleSource);

  console.log("Synced app config:");
  console.log("- app/src/generated/contracts.generated.ts");
  console.log("- app/src/generated/agent-plan-sample.generated.ts");
}

main();
